site_name: Documentación - Proyecto DS 2025-02
site_description: Portal central de documentación agregada por servicio
theme:
  name: material
nav:
  - Home: index.md
  - Arquitectura: arquitectura.md
  - "Lenguaje ubicuo": lenguaje-ubicuo.md
  - "Proyecto base": proyecto-base.md
  - "Proyecto DS 2025-02": "Proyecto DS 2025-02.pdf"
  - Negocio: guia-contexto-negocio.md
  - Técnica: guia-tecnica.md
  - ADRs:
    - "Global ADRs": adrs-global.md
  - Servicios:
    # Las secciones para cada servicio se crearán copiando docs/<service>/
    - "Descripción general": services/README.md
    - "Front end":
      - "Descripción": front-end/README.md
      - "Arquitectura": front-end/ARCHITECTURE.md
      - "Instalación / Setup": front-end/SETUP.md
      - "Mocks y adaptadores": front-end/MOCKS.md
      - "Lenguaje ubicuo": front-end/UBIQUITOUS_LANGUAGE.md
plugins:
  - search
extra:
  repo_url: https://github.com/eventmesh-lab/org-docs