site_name: Documentación - Proyecto DS 2025-02
site_description: Portal central de documentación agregada por servicio
theme:
  name: material
nav:
  - Home: index.md
  - Arquitectura: arquitectura.md
  - "Lenguaje ubicuo": lenguaje-ubicuo.md
  - "Proyecto base": proyecto-base.md
  - Negocio: guia-contexto-negocio.md
  - Técnica: guia-tecnica.md
  - ADRs:
    - "Global ADRs": adrs-global.md
  - Servicios:
    # Las secciones para cada servicio se crearán copiando docs/<service>/
    - "Descripción general": services/README.md
plugins:
  - search
extra:
  repo_url: https://github.com/eventmesh-lab/org-docs