site_name: Documentaci칩n - Proyecto DS 2025-02
site_description: Portal central de documentaci칩n agregada por servicio
theme:
  name: material
nav:
  - Home: index.md
  - Arquitectura: arquitectura.md
  - "Lenguaje ubicuo": lenguaje-ubicuo.md
  - "Proyecto base": proyecto-base.md
  - ADRs:
    - "Global ADRs": adrs-global.md
  - Servicios:
    # Las secciones para cada servicio se crear치n copiando docs/<service>/
    - "Descripci칩n general": services/README.md
plugins:
  - search
extra:
  repo_url: https://github.com/eventmesh-lab/org-docs